<section class="content-header">
    <h1>
        轮播图管理
        <small>
            {if $action == 'index'}
            轮播图列表
            {else}
            {if empty($item)}添加轮播图{else}修改轮播图{/if}
            {/if}
        </small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>轮播图管理</a></li>
        <li class="active">
            {if $action == 'index'}
            轮播图列表
            {else}
            {if empty($item)}添加轮播图{else}修改轮播图{/if}
            {/if}
        </li>
    </ol>
</section>