<!DOCTYPE HTML>
<html>

<head>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0,minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>绑定支付宝</title>
    <link href="/static/home/mobile/css/reset_5.css" rel="stylesheet" type="text/css"/>
    <link href="/static/home/mobile/css/style.css" rel="stylesheet" type="text/css"/>
    <link href="/static/home/mobile/css/new_style.css" rel="stylesheet" type="text/css"/>
    {include file='common/header'}
</head>
<body>
    <div class="site-header header-fixed">
        <a onclick="history.back()" class="back"></a>
        <div class="tit-name">绑定支付宝</div>
    </div>
    <div class="main bindMail">
        <div class="member-form">
            <div class="item-box">
                <input type="text" class="m_txt" placeholder="请输入支付宝账号" id="alipay_account"  value="{$member['alipay_account']?$member['alipay_account']:''}" {$member['is_bind_alipay']?'readonly':''}>
            </div>
            <div class="item-box">
                <input type="text" class="m_txt" placeholder="请输入真实姓名" id="alipay_realname"  value="{$member['alipay_realname']?$member['alipay_realname']:''}" {$member['is_bind_alipay']?'readonly':''}>
            </div>
        </div>
        <div class="member-btn">
            <input type="button" class="button1" value="确认" {$member['is_bind_alipay']?'disabled':''}>
        </div>
        <div class="member-ts">
            <label>温馨提示</label>
            <p>支付宝绑定后，不可修改</p>
        </div>
    </div>
    <script type="text/javascript">
        $(function () {
            //设置邮箱
            $('.button1').click(function () {
                var alipay_account = $('#alipay_account').val();
                var alipay_realname = $('#alipay_realname').val();
                $.post(
                    window.location.href,
                    {
                        alipay_account:alipay_account,
                        alipay_realname:alipay_realname
                    },
                    function (ret) {
                        message(ret.message,ret.redirect,ret.type);
                    },'json'
                );
            });
        });
    </script>
</body>
</html>