<section class="content-header">
    <h1>
        授权管理
        <small>
            {if $action == 'index'}
            授权列表
            {else}
            {if empty($item)}添加授权{else}修改授权{/if}
            {/if}
        </small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>授权管理</a></li>
        <li class="active">
            {if $action == 'index'}
            授权列表
            {else}
            {if empty($item)}添加授权{else}修改授权{/if}
            {/if}
        </li>
    </ol>
</section>