<section class="content-header">
    <h1>
        会员管理
        <small>
            {if $action == 'index'}
            会员列表
            {elseif $action == 'charge'}
            充值记录
            {elseif $action == 'cdkey'}
            激活码管理
            {elseif $action == 'cdkey1'}
            高级激活码管理
            {else}
            会员编辑
            {/if}
        </small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>会员管理</a></li>
        <li class="active">
            {if $action == 'index'}
            会员列表
            {elseif $action == 'charge'}
            充值记录
            {elseif $action == 'cdkey'}
            激活码管理
            {elseif $action == 'cdkey1'}
            高级激活码管理
            {else}
            编辑会员
            {/if}
        </li>
    </ol>
</section>