{include file="common/header"}
<div class="content-wrapper">
    {include file="recharge/nav"/}
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="nav-tabs-custom">
                    {include file="recharge/tabs"/}
                    <div class="tab-content">
                        <div class="page-content">
                            <div class="panel panel-info">
                                <div class="panel-heading">
                                    筛选
                                    <span class="pull-right">共有充值&nbsp;<font style="color: red;font-weight: bold;">{$total}</font>&nbsp;次</span>
                                </div>
                                <div class="panel-body">
                                    <form class="form-horizontal" method="get" role="form">
                                        <div class="form-group">
                                            <label class="col-xs-12 col-sm-3 col-md-2 control-label">关键词</label>
                                            <div class="col-sm-6 col-md-8 col-lg-8 col-xs-12">
                                                <input type="text" class="form-control" name="keyword" value="{$_GET['keyword']?$_GET['keyword']:''}" placeholder="请输入提现账号、姓名、手机号关键词">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-xs-12 col-sm-3 col-md-2 control-label">状态</label>
                                            <div class="col-sm-6 col-md-8 col-lg-8 col-xs-12">
                                                <label class="checkbox-inline">
                                                    <input type="checkbox" name="status[]" {if !empty($_GET['status']) && in_array(0,$_GET['status'])}checked{/if} value="0">
                                                    待审核
                                                </label>
                                                <label class="checkbox-inline">
                                                    <input type="checkbox" name="status[]" {if !empty($_GET['status']) && in_array(1,$_GET['status'])}checked{/if} value="1">
                                                    已发放
                                                </label>
                                                <label class="checkbox-inline">
                                                    <input type="checkbox" name="status[]" {if !empty($_GET['status']) && in_array(-1,$_GET['status'])}checked{/if} value="-1">
                                                    审核未通过
                                                </label>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="col-sm-6 col-md-8 col-lg-8 col-xs-12 col-md-offset-2 col-lg-offset-2 col-sm-offset-4">
                                                <button class="btn btn-primary"><i class="fa fa-search"></i> 搜索</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <form method="post" class="form-horizontal" id="display_form">
                                <div class="panel panel-default ">
                                    <div class="table-responsive panel-body">
                                        <table class="table table-hover">
                                            <thead class="navbar-inner">
                                            <tr>
                                                <th style="width: 45px">删?</th>
                                                <th>提现ID</th>
                                                <th>用户名</th>
                                                <th>账号</th>
                                                <th>充值金额</th>
                                                <th>支付时间</th>
                                                <th>真实姓名</th>
                                                <th>状态</th>
                                                <th>申请时间</th>
                                                <th>操作</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {if !empty($list)}
                                                {volist name="list" id="item"}
                                                <tr>
                                                    <td>
                                                        <input type="checkbox" name="ids[]" value="{$item['id']}">
                                                    </td>
                                                    <td>{$item['id']}</td>
                                                    <td>{$item['username']}</td>
                                                    <td>{$item['account']}</td>
                                                    <td>
                                                        <label class="label label-success">{$item['credit2']}</label>
                                                    </td>
                                                    <td>{$item['pay_time']}</td>
                                                    <td>{$item['realname']}</td>
                                                    <td>
                                                        {if $item['status'] == 0}
                                                        <label class="label label-info">待审核</label>
                                                        {elseif $item['status'] == 1}
                                                        <label class="label label-success">已发放</label>
                                                        {else}
                                                        <label class="label label-danger">审核未通过</label>
                                                        {/if}
                                                    </td>
                                                    <td>
                                                        {$item.create_time}
                                                    </td>
                                                    <td>
                                                        <a href="{:U('post', 'id=' . $item['id'])}" class="btn btn-sm btn-success">审核</a>
                                                    </td>
                                                </tr>
                                                {/volist}
                                                <tr>
                                                    <td>
                                                        <input type="checkbox" onclick="var ck = this.checked;$('table').find(':checkbox').each(function(){this.checked = ck});">
                                                    </td>
                                                    <td colspan="6">
                                                        <button class="btn btn-sm btn-danger" name="submit" type="button">删除</button>
                                                    </td>
                                                </tr>
                                            {/if}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </form>
                            {$pager}
                            <script type="text/javascript">
                                $(function () {
                                    $('button[name="submit"]').bind('click',function() {
                                        if (confirm('删除后不可恢复，您确定删除吗？')) {
                                            $.post(
                                                window.location.href,
                                                $('#display_form').serialize(),
                                                function (ret) {
                                                    message(ret.message, ret.redirect, ret.type);
                                                }, 'json'
                                            );
                                        }
                                    });
                                });
                            </script>
                        </div>
                    </div>
                    <!-- /.tab-content -->
                </div>
                <!-- /.nav-tabs-custom -->
            </div>
            <!-- /.col -->
        </div>
    </section>
</div>
{include file="common/footer"}
