<section class="content-header">
    <h1>
        充值管理
        <small>
            {if $action == 'index'}
            充值列表
            {else}
            {if empty($item)}添加充值{else}修改充值{/if}
            {/if}
        </small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>充值管理</a></li>
        <li class="active">
            {if $action == 'index'}
            充值列表
            {else}
            审核充值
            {/if}
        </li>
    </ol>
</section>