<!DOCTYPE HTML>
<html>

    <head>
        <meta name="apple-mobile-web-app-capable" content="yes">  
        <meta name="viewport" content="width=device-width, initial-scale=1.0,minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>推推-微信投票,微信助力,APP下载,游戏推广……可以拉票推广也可以赚钱</title>
        {include file='common/header'}
        <style type="text/css">
.paging {
    padding: 30px 0;
}
.data_red_bg{
    display:block;
    background: #f66364;
    color:#fff;
    padding:11px 11px 0;
    position:relative;
}
.data_red_bg_cont{
    border-bottom:1px solid #ff8788;
    padding:0 0 16px 0;
}
.data_red_bg .data_img{
    float:left;
    width:53px;
    height:;;
    padding: 0 10px 0 10px;
    width:53px;
    height:53px;
}
.data_img img{
    width:100%;
    height:100%;
    border-radius:100%;
}
.data_infor{
    position:relative;
}
/* infor */
.data_infor_wrapper{
    float:left;
    position:relative;
}
.data_use_name{
    float:left;
    max-width:142px;
    font-size:15px;
    line-height:30px;
    color:#fff;
    margin-right:16px;
    text-overflow:ellipsis;
    overflow:hidden;
    white-space:nowrap;
}
.data_infor_title,.data_all{
    font-size:11px;
    line-height:24px;
    color:#fbc5bf;
}
.data_all span{
    display:inline-block;
    color:#fff;
    width:1.8rem;
    font-size:11px;
    text-align:center;
}

/* top相关操作按钮   */
.top_btn_one_wrap,.top_btn_two_wrap{
    position:absolute;
    top:14.5px;
    right:21px;
}
.top_btn_two_wrap{
    top:14.5px;
}
.top_btn_each{
    width:50px;
    height:20px;
    border:1px solid #fff;
    text-align:center;
    font-size:13px;
    line-height:20px;
    border-radius:20px;
    cursor:pointer;
    margin:3px 0;
}
.top_btn_each_2{
    width:72px;
}
/* 相关状态信息   */
.user_infor_wrap{
    padding:10px 11px;
    color:#fff;
    background-color:#f66364;
}
.each_user_infor{
    float:left;
    width:33.33%;
    font-size:13px;
    line-height:24px;
}
.each_infor_title{
    float:left;
    color:#ffc7c7;
    padding: 0 6px 0 4px;
}
.each_infor_title span{
    padding:0 20px 0 0;
}
.each_infor_num{
    float:left;
    color:#fff;
}
        </style>
    </head>

    <body>
        <header class="site-header header-fixed">
            <a onclick="window.history.back();" class="back"></a>
            <div class="tit-name">{$member.username}的店铺</div>
        </header>
        <div class="main inivteFriend">
            <!-- 个人头像部分-->
            <div class="data_red_bg">
                <div class="data_red_bg_cont cl">
                    <div class="data_img">
                        <img src="{:to_media($member['avatar']?$member['avatar']:'')}" id="show_img" onerror="javascript:this.src='/uploads/avatar.png';" alt='用户头像' />
                    </div>
                    <div class="data_infor_wrapper">
                        <div class="data_infor cl">
                            <div class="data_use_name">{$member.username}</div>
                        </div>
                        <div class="data_all">
                            ID:{$member.uid}&nbsp;&nbsp;&nbsp;&nbsp;
                        </div>
                        <div class="data_all data_all_time">
                        </div>
                    </div>
                    <div class="top_btn_one_wrap">
                        {if $isFollow}
                        <div class="top_btn_each" onclick="delFollow('{$member.uid}');">取消</div>
                        {else}
                        <div class="top_btn_each" onclick="followUser('{$member.uid}');">+关注</div>
                        {/if}
                    </div>              
                </div>
            </div>
            
            <!-- 相关状态信息 -->
            <div class="user_infor_wrap  cl">
                <div class="each_user_infor">
                    <div class="each_infor_title">发任务</div>
                    <div class="each_infor_num">{$task_num}个</div>
                </div>
                <div class="each_user_infor">
                    <div class="each_infor_title">接任务</div>
                    <div class="each_infor_num">{$join_num}单</div>
                </div>
            </div>

            <div class="bk10">
            </div>
            <div class="task-list">
                {if !empty($tasks)}
                <div class="new-task-list">
                    <ul>
                        {include file='user/_task_list'}
                    </ul>
                </div>
                <div class="paging" style="display: block;">
                    <span class="paging-prev">上一页</span>
                    <span class="paging-num-total">
                            <select name="page" class="paging-selct">
                                {for start="1" end="$pageCount+1"}
                                <option value="{$i}">{$i}</option>
                                {/for}
                            </select>
                        </span>
                    <span class="paging-next" data-page="{$pageCount}">下一页</span>
                    <form id="page_form">
                        <input type="hidden" name="page" value="1">
                    </form>
                </div>
                {/if}
            </div>
        </div>
        {include file='common/footer'}

        <script type="text/javascript" src="/static/home/mobile/js/mytask.js?v=4"></script>
        <script type="text/javascript">
        var saveFlag = "0";
        function followUser(user_id){
            if(saveFlag == '1'){
                return false;
            }
            saveFlag = "1";
            Common.loading.show();
            $.post('/home/fans/followUser.html', { user_id: user_id }, function(res) {
                message(res.message,res.redirect,res.type);
                Common.loading.hide();
            });     
        }

        function delFollow(user_id){
            if(saveFlag == '1'){
                return false;
            }
            saveFlag = "1";
            Common.loading.show();
            $.post('/home/fans/unFollowUser.html', { user_id: user_id }, function(res) {
                message(res.message,res.redirect,res.type);
                Common.loading.hide();
            });     
        }
        </script>
</body>

</html>