<section class="content-header">
    <h1>
        提现管理
        <small>
            {if $action == 'index'}
            提现列表
            {else}
            {if empty($item)}添加提现{else}修改提现{/if}
            {/if}
        </small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>提现管理</a></li>
        <li class="active">
            {if $action == 'index'}
            提现列表
            {else}
            审核提现
            {/if}
        </li>
    </ol>
</section>