<section class="content-header">
    <h1>
        邀请管理
        <small>
            {if $action == 'index'}
            邀请列表
            {else}
            {if empty($item)}添加邀请{else}修改邀请{/if}
            {/if}
        </small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>邀请管理</a></li>
        <li class="active">
            {if $action == 'index'}
            邀请列表
            {/if}
        </li>
    </ol>
</section>