<html lang="zh-cn"><head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
	<title>糟糕，出错了</title>
	<meta name="format-detection" content="telephone=no, address=no">
	<meta name="apple-mobile-web-app-capable" content="yes"> <!-- apple devices fullscreen -->
	<meta name="apple-touch-fullscreen" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
	<meta name="keywords" content="郑州慕马树网络科技有限公司，河南郑州微信第三方开发，河南郑州小程序开发，河南郑州游戏开发，河南郑州手机app定制开发，河南郑州网站建设，河南郑州服务器维护等，全心全意服务，客户至上，售后无忧，0371-55297759">
	<meta name="description" content="郑州慕马树网络科技有限公司，河南郑州微信第三方开发，河南郑州小程序开发，河南郑州游戏开发，河南郑州手机app定制开发，河南郑州网站建设，河南郑州服务器维护等，全心全意服务，客户至上，售后无忧，0371-55297759">
	<link href="/static/error/mobile/common.min.css" rel="stylesheet">
</head>
<body style="padding-bottom: 20px;">
<div class="mui-content fadeInUpBig animated mui-backdrop" style="background-color: rgb(239, 239, 244);">
	<div class="mui-content-padded">
		<div class="mui-message">
			<div class="mui-message-icon t21"><span class="mui-msg-error"></span></div>
			<h4 class="title"><?php echo $message;?></h4>
			<p class="mui-desc"></p>
			<div class="mui-button-area" onclick="history.back()">
                <a href="javascript:;" class="mui-btn mui-btn-success mui-btn-block">确定</a>
			</div>
		</div>
	</div>
</div>
</body>
</html>