<section class="content-header">
    <h1>
        任务管理
        <small>
            {if $action == 'index'}
            任务列表
            {else}
            {if empty($item)}添加任务{else}修改任务{/if}
            {/if}
        </small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> 任务管理</a></li>
        <li class="active">
            {if $action == 'index'}
            任务列表
            {else}
            查看任务
            {/if}
        </li>
    </ol>
</section>