<footer class="new-footer">
    <ul>
        <li>
            <a href="/home/index.html">
                <img {if condition="$controller neq 'index'"}class="gray"{/if} src="/static/home/mobile/picture/home.png" />
                <span>首页</span>
            </a>
        </li>
        <li>
            <a href="/home/activity.html">
                <img  {if condition="$controller neq 'activity'"}class="gray"{/if}  src="/static/home/mobile/picture/activity.png" />
                <span>活动</span>
            </a>
        </li>
        <li>
            <a href="/home/task/add.html">
                <span class="add-span"></span>
                <span>发布</span>
            </a>
        </li>
        <li>
            <a href="/home/invite.html">
                <img  {if condition="$controller neq 'invite'"}class="gray"{/if}  src="/static/home/mobile/picture/news.png" />
                <span>收徒</span>
            </a>
        </li>
        <li>
            <a href="/home/account.html">
                <img {if condition="$controller neq 'account'"}class="gray"{/if}  src="/static/home/mobile/picture/users.png" />
                <span>我的</span>
            </a>
        </li>
    </ul>
</footer>