<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/html">

<head>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="viewport" content="width=device-width, initial-scale=1.0,minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>新增反馈</title>
    {include file='common/header'}
    <link href="/static/home/mobile/css/reset_5.css" rel="stylesheet" type="text/css"/>
    <link href="/static/home/mobile/css/style.css" rel="stylesheet" type="text/css"/>
    <link href="/static/home/mobile/css/new_style.css" rel="stylesheet" type="text/css"/>
</head>
<body>
    <div class="site-header header-fixed">
        <a onclick="history.back()" class="back"></a>
        <div class="tit-name">新增反馈</div>
    </div>
    <div class="main bindMail">
        <div class="member-form">
            <div class="item-box" style="height: auto;">
                <textarea id="content" name="content" placeholder="请输入您需要反馈的内容" style="width: 100%;height: 200px;"></textarea>
            </div>
        </div>
        <div class="member-btn">
            <button type="button" class="button1 js-bind"  {$member['is_bind_email']?'disabled':''}>确认</button>
        </div>
       <!--  <div class="member-ts">
            <label>温馨提示</label>
            <p></p>
        </div> -->
    </div>
    <script type="text/javascript">
        $(function () {
            //设置邮箱
            $('.js-bind').click(function () {
                var content = $('#content').val();
                if ($.trim(content) == "") {
                    message("请输入您需要反馈的内容","","error");
                    return;
                }
                $.post(
                    '/home/feedback/save',
                    {content: content},
                    function (ret) {
                        message(ret.message,ret.redirect,ret.type);
                    },'json'
                );
            });
        });
    </script>
</body>
</html>