<!DOCTYPE HTML>
<html>

    <head>
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="viewport" content="width=device-width, initial-scale=1.0,minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>邀请好友</title>
        {include file='common/header'}
        <link rel="shortcut icon" href="clientapp/images/new_images/favicon.ico" />
        <link href="/static/home/mobile/css/reset_5.css" rel="stylesheet" type="text/css" />
        <link href="/static/home/mobile/css/style.css" rel="stylesheet" type="text/css" />
        <link href="/static/home/mobile/css/new_style.css" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" href="/static/home/mobile/css/font-awesome.min.css">
        <link rel="stylesheet" href="/static/home/mobile/css/new_page.css">
        <link rel="stylesheet" href="/static/home/mobile/css/layui.css">
        <style type="text/css">
        .mx_list li {
            min-height: 26px;
            line-height: 26px;
        }
        </style>
    </head>
    <body>
        <header class="site-header header-fixed">
            <a onclick="window.history.back();" class="back"></a>
            <div class="tit-name">
                邀请好友
            </div>
        </header>
        <div class="main inviteList">
            <div class="member-tab">
                <ul class="add_friend_tab">
                    <li>
                        <a href="/home/invite.html"> <span>邀请好友</span></a>
                    </li>
                    <li class="active">
                        <span>邀请记录</span>
                    </li>
                    <li>
                        <a href="/home/invite/gold.html"> <span>邀请返利</span></a>
                    </li>
                </ul>
            </div>
            <div class="update-box mx_list" id="table">
                <ul id="flow">
                </ul>
                <!-- <div class="alipa-box">
                    <div class="task-none" style="display: none;text-align: center;">暂无数据</div>
                </div> -->
            </div>
        </div>
        {include file="common/footer"/}

<script type="text/javascript" src="/static/home/mobile/js/layui/layui.js"></script>
<script type="text/javascript">
$(function(){
        //流加载
        layui.use('flow', function(){
            var flow = layui.flow;
            flow.load({
                    elem: '#table'
                    ,done: function(page, next){
                            var lis = [];
                            $.get('/home/invite/silver_ajax?page='+page, function(res){
                                layui.each(res.data.data, function(index, item){
                                    $("#flow").append('<li><b><time>'+item.create_time+'</time></b><p>邀请用户：'+item.invite_username+'<span>'+(item.invite_username ? '成功邀请用户：'+item.invite_username+'，编号：'+item.invite_uid : '')+'</span></p>    </li>');
                                });
                                next(lis.join(''), res.data.length > 0 ? true : false);
                            });
                    }
            });
        });
});
</script>
</body>
</html>