{include file="common/header"}
<div class="content-wrapper">
    {include file="auth_admin/nav"/}
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="nav-tabs-custom">
                    {include file="auth_admin/tabs"/}
                    <div class="tab-content">
                        <div class="page-content">
                            <div class="panel panel-info">
                                <div class="panel-heading">筛选</div>
                                <div class="panel-body">
                                    <form class="form-horizontal" role="form">
                                        <div class="form-group">
                                            <label class="col-xs-12 col-sm-3 col-md-2 control-label">关键词</label>
                                            <div class="col-sm-6 col-md-8 col-lg-8 col-xs-12">
                                                <input type="text" class="form-control" name="keyword" value="{$_REQUEST['keyword']?$_REQUEST['keyword']:''}" placeholder="请输入搜索关键词">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="col-sm-6 col-md-8 col-lg-8 col-xs-12 col-md-offset-2 col-lg-offset-2 col-sm-offset-4">
                                                <button class="btn btn-default"><i class="fa fa-search"></i> 搜索</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <form method="post" class="form-horizontal" id="display_form">
                                <div class="panel panel-default ">
                                    <div class="table-responsive panel-body">
                                        <table class="table table-hover">
                                            <thead class="navbar-inner">
                                            <tr>
                                                <th style="width: 45px">删?</th>
                                                <th>ID</th>
                                                <th>头像</th>
                                                <th>用户名</th>
                                                <th>姓名</th>
                                                <th>邮箱</th>
                                                <th>手机号码</th>
                                                <th>状态</th>
                                                <th>操作</th>
                                            </tr>
                                            </thead>
                                            {if !empty($list)}
                                            <tbody>
                                            {volist name="list" id="item" key="index" }
                                            <tr>
                                                <td>
                                                    {if $item['id'] != 1}
                                                    <input type="checkbox" name="ids[]" value="{$item['id']}">
                                                    {else}
                                                    -
                                                    {/if}
                                                </td>
                                                </td>
                                                <td>{$item['id']}</td>
                                                <td><img src="/uploads/{$item.avatar|default='avatar.png'}" style="width:50px;border-radius:50%;" /></td>
                                                <td>{$item['username']}</td>
                                                <td>{$item.nickname}</td>
                                                <td>{$item.email}</td>
                                                <td>{$item.mobile}</td>
                                                <td>
                                                    {if $item['is_check'] == 1}
                                                    <span class="label label-success">启用</span>
                                                    {else}
                                                    <span class="label label-default">禁用</span>
                                                    {/if}
                                                </td>
                                                <td>
                                                    <a class="btn btn-primary btn-sm" href="{:U('authgroup', 'id=' . $item['id'])}">授权角色</a> 
                                                    <a href="{:U('post', 'id=' . $item['id'])}" class="btn btn-sm btn-success">编辑</a>
                                                </td>

                                            </tr>
                                            {/volist}
                                            <tr>
                                                <td>
                                                    <input type="checkbox" onclick="var ck = this.checked;$('table').find(':checkbox').each(function(){this.checked = ck});">
                                                </td>
                                                <td colspan="51">
                                                    <button name="submit" class="btn btn-sm btn-danger" type="button">删除</button>
                                                </td>
                                            </tr>
                                            </tbody>
                                            {/if}
                                        </table>
                                    </div>
                                </div>
                            </form>
                            {$pager}
                            <script type="text/javascript">
                                $(function () {
                                    $('button[name="submit"]').bind('click',function() {
                                        if (confirm('删除后不可恢复，您确定删除吗？')) {
                                            $.post(
                                                window.location.href,
                                                $('#display_form').serialize(),
                                                function (ret) {
                                                    message(ret.message, ret.redirect, ret.type);
                                                }, 'json'
                                            );
                                        }
                                    });
                                });
                            </script>
                        </div>
                    </div>
                    <!-- /.tab-content -->
                </div>
                <!-- /.nav-tabs-custom -->
            </div>
            <!-- /.col -->
        </div>
    </section>
</div>
{include file="common/footer"}
