<section class="content-header">
    <h1>
        管理员管理
        <small>
            {if $action == 'index'}
            管理员列表
            {else}
            {if empty($item)}添加管理员{else}修改管理员{/if}
            {/if}
        </small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>管理员管理</a></li>
        <li class="active">
            {if $action == 'index'}
            管理员列表
            {else}
            {if empty($item)}添加管理员{else}修改管理员{/if}
            {/if}
        </li>
    </ol>
</section>