<section class="content-header">
    <h1>
        公告管理
        <small>
            {if $action == 'index'}
            公告列表
            {else}
            {if empty($item)}添加公告{else}修改公告{/if}
            {/if}
        </small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>公告管理</a></li>
        <li class="active">
            {if $action == 'index'}
            公告列表
            {else}
            {if empty($item)}添加公告{else}修改公告{/if}
            {/if}
        </li>
    </ol>
</section>