<!DOCTYPE HTML>
<html>
	<head>
		<meta name="apple-mobile-web-app-capable" content="yes">  
        <meta name="viewport" content="width=device-width, initial-scale=1.0,minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<title>提现</title>
        {include file='common/header'}
		<link href="/static/home/mobile/css/reset_5.css" rel="stylesheet" type="text/css" />
		<link href="/static/home/mobile/css/style.css" rel="stylesheet" type="text/css" />
		<link rel="stylesheet" href="/static/home/mobile/css/font-awesome.min.css">
		<link rel="stylesheet" type="text/css" href="/static/home/mobile/css/new_page.css" />
		<script type="text/javascript">
			function check() {
				if($('#total_fee').val() == '') {
					$('#error').text('充值金额还没填写');
					$('#error').show();
					return false;
				} else {
					$('#error').text('');
					$('#error').hide();
					return true;
				}
			}
		</script>
		<style type="text/css">
			.new-header .dowm-btn {
				bottom: 0;
			}
			
			.new-header .back {
				bottom: 18px;
			}
		</style>
	</head>
	<body>
		<header class="new-header" style="padding-top: 15px;">
			<a onclick="history.back()" class="back">
				<img src="/static/home/mobile/picture/return.png" />
			</a>
			<div class="tit-name">提现</div>
			<span class="dowm-btn publish-task-btn">
				<a href="goldDetail.html" class="sc" style="color: #fff;">明细</a>
			</span>
		</header>

		<div class="new-top-up">
			<div class="update-box" id="hasZfb" style="display: none;">
				<div class="zfb-count">
					<img src="/static/home/mobile/picture/wechat.png" />微信账号：<span></span>
				</div>
				<div class="user-gold">
					<span>余额：<span class="user-gold-money"></span></span>
					<span class="gold-all-btn">全部</span>
				</div>
				<div class="member-form">
					<div class="item-box"><span>￥</span><input type="text" class="m_txt" placeholder="请输入取现金额" id="goldNum" oninput="CashValue.computeMoney()"></div>
					<div class="tixian_txt">最低一元提现，每天可提现，24小时到账</div>
					<div class="member-btn"><input type="button" class="button1" onclick="CashValue.draw();" value="确认"></div>
				</div>
				<div id="error" style="display:none;"></div>
			</div>
			<div class="update-box" id="noZfb-phone">
				<p>温馨提示：</p>
				<ul>
					<li class="bing-weixin">首次进行微信提现请在微信公众号“推推官微”进行提现
					</li>
					<li class="check-count">确保关注公众号“推推官微”，否则转账错误概不负责</li>
					<!--<li class="check-count">请确定账号信息无误！</li>-->
				</ul>
			</div>
		</div>
        {include file='common/footer'}
    </body>
</html>