{include file="common/header"}
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            资料设置
            <small>资料设置</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> 资料设置</a></li>
            <li class="active">资料设置</li>
        </ol>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="nav-tabs-custom">
                    <!-- Tabs within a box -->
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#base" data-toggle="tab">资料设置</a></li>
                    </ul>
                    <div class="page-content" style="padding: 20px 0">
                        <form method="post" class="form-horizontal form" id="post_form">
                            <div class="tab-content">
                                <div class="tab-pane active" id="base">
                                    <div class="form-group">
                                        <label class="col-xs-12 col-sm-3 col-md-2 control-label">用户名</label>
                                        <div class="col-sm-8 col-xs-12">
                                            <input readonly type="text" class="form-control" value="{$admin['username']?$admin['username']:''}">
                                            <span class="help-block">用户名不能修改</span>
                                        </div>
                                    </div>
                                    {:tpl_upload_image(['name'=>'avatar','title' => '头像','value'=>!empty($admin['avatar'])?to_media($admin['avatar']):'','placeholder'=>'请上传头像','help'=>'建议宽高：50*50'])}
                                    <div class="form-group">
                                        <label class="col-xs-12 col-sm-3 col-md-2 control-label">新密码</label>
                                        <div class="col-sm-8 col-xs-12">
                                            <input type="text" class="form-control" name="password" placeholder="请输入新密码">
                                            <span class="help-block">不修改密码时，可以不需要填写</span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-xs-12 col-sm-3 col-md-2 control-label">确认新密码</label>
                                        <div class="col-sm-8 col-xs-12">
                                            <input type="text" class="form-control" name="password_confirm" placeholder="请再次输入新密码">
                                            <span class="help-block">不修改密码时，可以不需要填写</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-8 col-xs-12 col-sm-offset-2">
                                    <button type="button" name="submit" class="btn btn-primary">提交</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <script type="text/javascript">
                        $(function () {
                            //提交分类信息
                            $("button[name='submit']").click(function () {
                                $.post(
                                    window.location.href,
                                    $('#post_form').serialize(),
                                    function (res) {
                                        message(res.message,res.redirect,res.type)
                                    },'json'
                                );
                            });
                        });
                    </script>
                </div>
                <!-- /.nav-tabs-custom -->
            </div>
            <!-- /.col -->
        </div>
    </section>
</div>
{include file="common/footer"}
